### Get list of games, should return 200 ok
GET http://localhost:4444/api/games

### Get specific game, should return 200 ok
GET http://localhost:4444/api/games/1

### Try get faulty game id, should return 404 not found
GET http://localhost:4444/api/games/4123123

### POST a new game to be added to list, should return 200 ok
POST http://localhost:4444/api/games
Content-Type: application/json

{
    "title": "Starcraft", "genre": "RTS", "price": 15
}

### POST a new game to be added to list with invalid info, should return 400 bad request
POST http://localhost:4444/api/games
Content-Type: application/json

{
    "asd": "Starcraft", "genre": "R", "price": 15
}

### post new game with missing attribute, should also return 400
POST http://localhost:4444/api/games
Content-Type: application/json

{
    "genre": "RTS", "price": 15
}


### DELETE a game by supplying ID as a number in the url, should return 200 ok
DELETE http://localhost:4444/api/games/2

### test if supplying a nonexisting id returns error, should return 404 not found
DELETE http://localhost:4444/api/games/2521342


### Update a game in the list using ID and a body with JSON data, should return OK
PUT http://localhost:4444/api/games/1
Content-Type: application/json

{
    "title":"Natural Selection", "genre":"RTS", "price":11
}

### Faulty update data, testing validation (negative price), should return 400 bad request
PUT http://localhost:4444/api/games/1
Content-Type: application/json

{
    "title":"Natural Selection", "genre":"RTS", "price":-1

}

### Faulty update data, testing validation (missing field), should return 400 bad request
PUT http://localhost:4444/api/games/55
Content-Type: application/json

{
    "title":"Natural Selection", "price":-1

}

### Faulty ID in URL, testing error catching (no game with ID in URL), should return 404 not found
PUT http://localhost:4444/api/games/1546645
Content-Type: application/json

{
    "title":"Natural Selection", "genre":"RTS", "price":11
}